### ISSUE TITLE
BGM2AT 

### ISSUE THREAD

**Issue by btrainee** [chenlianfu/geta#4]
hello,
when I run BGM2AT of 5.augustus, there is no some subscripts called by, like, gff2gbSmallDNA.pl,randomSplit.pl.where can I find these?help…

**Comment by chenlianfu** [comment]
you can find them in augustus software. add the augustus/scripts directory into $PATH to solve your problem.

**Comment by chenlianfu** [comment]
you can find them in augustus software. add the augustus/scripts directory into $PATH to solve your problem.
